context:
  version: "2.9.0"

package:
  name: preconstruct
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@preconstruct/cli/-/cli-${{ version }}.tgz
  sha256: fc19370bc041d5ecbe2b6241a6f58a432f35e6c4ff0aac4e679257095afa31e3

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - preconstruct --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Dev and build your code painlessly in monorepos
  homepage: https://github.com/preconstruct/preconstruct
  repository: https://github.com/preconstruct/preconstruct

extra:
  recipe-maintainers:
    - danielnachun
